### ISSUE TITLE
Roadmap to 0.1.1

### ISSUE THREAD

**Issue by edwin0cheng** [edwin0cheng/unrust#13]
The goal of 0.1.1 is making to be able to making simple tower stacking game (Similar to this one (http://m.softgames.de/games/stack-tower).

### TODO

- [x] Change name to "unrust"
- [x] Alpha sorting
- [x] GameObject hierarchy 
- [x] Add Sponza scene example
- [x] Add DDS Support
- [x] Shadow map / (Hard and Soft)
- [x] Basic sound support (sub-crate)
- [x] Skybox
- [x] Added World module to improve usage : [basic.rs](https://github.com/edwin0cheng/unrust/blob/master/examples/basic.rs)
- [x] Remove [[bin]] and move the box demo to example
- [x] Setup CI 
- [x] Drop naglebra and use cgmath instead. 
- [x] Added #include support in uni_glsl

### Next milestone
- [ ] Sky Light 
  * We should decide how the 'standard material' works first to implement this.

#### The following items maybe fixed by switch to SDL2, which right now block by winit crate.
- [ ] Able to us resizable / fixed window ( unimplemented in winit for Windows and Macs )
- [ ] Able to toggle fullscreen ( unimplemented in winit for Windows and Macs )

**Comment by edwin0cheng** [comment]
@jice-nospam Do you  have any features you want to use / test first ?

**Comment by jice-nospam** [comment]
From a user point of view : being able to use resizable/fixed window, full screen, being able to switch fullscreen/resolution while ingame. Maybe sound support should be in a separate crate or at least  a subcrate

**Comment by edwin0cheng** [comment]
Agreed, added to the list, thank you so much.

**Comment by jice-nospam** [comment]
I'll let you work on engine structural items (alpha sorting, GO hierarchy), and I'll tackle lesser things :) Starting with fullscreen stuff.

Also we should work to make engine easier to use. Right now, a rotating cube requires 250 lines of code (not counting appfs.rs). We should be able to lower that.
Another thought. Shouldn't appfs.rs be on engine side ?At least as default implementation

**Comment by edwin0cheng** [comment]
Cool .. And the "Added App or World module to improve usage" is going to tackle this part. Would move all the Game struct and related AppFs to world mod parallel to engine. And change the add a IGameObject trait (or something like this to let user update its own component.

**Comment by jice-nospam** [comment]
awesome!

**Comment by jice-nospam** [comment]
well fullscreen will have to wait because it's not yet implemented for windows in winit :
https://github.com/tomaka/winit/blob/d92666c1880bad27d624dbbda2e14adc2b72e557/src/platform/windows/window.rs#L288

**Comment by edwin0cheng** [comment]
And i just checked too, fullscreen and set_decoration (needs for fixed & sized window) is not implemented neither in Windows and Macs , :(

**Comment by edwin0cheng** [comment]
Added World module and changed all examples code. It is much simpler.  I added a basic example which show a rotating cube, it is only 140 lines. (included a directional light, input handling etc..)

**Comment by jice-nospam** [comment]
Nice! Also dependencies have been greatly simplified. GG

**Comment by jice-nospam** [comment]
Did you already start working on the sound support? I have a rough working proof in concept low level wrapper that uses cpal for the native side and web audio api for the web part. I can create a pull request if you don't have other plans for the sound API

**Comment by edwin0cheng** [comment]
Perfect timing, i am still working on the Sponza scene example, and totally no idea what the sound support would be, so please create a pull request ^^

**Comment by paulirotta** [comment]
Just a quick THANKS. I'm excited about this as I start to dig in. It seems the positioning and timing is spot on.

**Comment by edwin0cheng** [comment]
@paulirotta Thanks :)

And you can try out the sponza  demo too `cargo web start --examples sponza --release` to see how cool rust-wasm support is :)

**Comment by jice-nospam** [comment]
You can also check how well the lower packages (uni-xxx) perform in an actual 2D game here : http://roguecentral.org/~jice/viper2/?cart=celeste

**Comment by edwin0cheng** [comment]
Sorry for my off-topic question:

@jice-nospam I tried a lot of times , but still fail to jump to top of the first screen ...How to do that?

**Comment by jice-nospam** [comment]
@edwin0cheng 
the x key does a dash, the c key a standard jump.
You can search "celeste pico8 speedrun" videos on youtube to see how to pass the levels

**Comment by edwin0cheng** [comment]
@jice-nospam thanks :)

**Comment by edwin0cheng** [comment]
I just added mipmap and DDS support. It pump the webgl version Sponza example from 25fps to 35 fps , yeah :)

**Comment by edwin0cheng** [comment]
Im planning to drop the nalgebra and use cgmath instead. Would it breaks your works ? @jice-nospam 

https://github.com/edwin0cheng/unrust/issues/35

**Comment by jice-nospam** [comment]
Nope. Since I'm on a 2D project, I'm using using the lower crates so far.

**Comment by jice-nospam** [comment]
Do you already have some plan for the sound crate for 0.1.1 ? Basic stereo or do you need 3D support right from the start ? Are we writing a system by our own or are we trying to have a working native/wasm32 openal wrapper ? @edwin0cheng

**Comment by edwin0cheng** [comment]
I still dont have any plan for the sound crate, but i think basic stereo sound is okay for now.
And i would avoid to write a new system if it is possible, but which openal wrapper should we pick ?

**Comment by jice-nospam** [comment]
I've already used alto successfully but I've no idea what work would be needed (or even if it's doable) to make it work on wasm32 side. On another hand, it seems fmod is now available for javascript : http://www.html5gamedevs.com/topic/28454-fmod-studio-api-now-available-for-html5/
I'll investigate this

**Comment by edwin0cheng** [comment]
But fmod is not an open source license, which means its not suitable for our project. On the other hand, alto seem legit but we have to port the whole openal api on it. (although it has emscripten support, but i will avoid to use emscripten too, as this project should be 100% rust-unknown-unknown target)

**Comment by jice-nospam** [comment]
Yeah that's the main issue with sound support right now. I didn't find any library that was wasm32-unknown-unkown compatible. Even current uni-snd required to write the web part from scratch.

**Comment by jice-nospam** [comment]
It seems using alto on native side and some javascript library still to be found on wasm32 side is the way to go. There's a list here :
https://www.egrappler.com/wonderful-javascript-audio-libraries-for-developers/

**Comment by edwin0cheng** [comment]
Right now uni-snd handled very low level sound support already, maybe we could target the new sound-crate to very high level crate which just provide very basic function at this moments.
For examples : 

fn play_sound_2D(path: &str, loop: Loop)
fn stop_sound_2D(path: &str)
fn set_volume(f: f32)

etc..

**Comment by edwin0cheng** [comment]
> It seems using alto on native side and some javascript library still to be found on wasm32 side is the way to go. 

But right now it is no way to add js library in stdweb build pipeline...

**Comment by jice-nospam** [comment]
> fn play_sound_2D(path: &str, loop: Loop)
fn stop_sound_2D(path: &str)
fn set_volume(f: f32)

This can be very easily done with uni-snd. The main problem is not sound output, it's more the handling of the sound files cache.
I would rather go for this kind of API :
```
fn load_sound(path:&str) -> usize // load into cache and returns an id
fn play_sound(id: usize, channel: Option<usize>, loop: bool, priority: usize, balance: f32) // start a sound on a specific channel or on the first free channel if channel==None. If no channel is free, use a channel playing a sound with lower priority. balance = left/right balance [0.0-1.0]
fn stop _sound(channel: usize) 
fn unload_sound(id: usize) // remove data from the cache
```

**Comment by edwin0cheng** [comment]
Thats good for me now, as we can refactor it later.
However, how about use a NewType Pattern here :
```
struct SoundHandle(usize);
enum Channel {...};

fn load_sound(path:&str) -> SoundHandle // load into cache and returns an id
fn play_sound(id: SoundHandle, channel: Option<Channel>, loop: bool, priority: usize, balance: f32) // start a sound on a specific channel or on the first free channel if channel==None. If no channel is free, use a channel playing a sound with lower priority. balance = left/right balance [0.0-1.0]
fn stop _sound(channel: Channel) 
fn unload_sound(id: SoundHandle) // remove data from the cache
```

**Comment by jice-nospam** [comment]
Looks good !

**Comment by edwin0cheng** [comment]
I just changed all nalgerba math to cgmath. And move the ncollide and related stuffs from cargo `dependency` to `dev-dependency` (which only used in boxes example for physic demo). 

It means we do not need to add that `[replace]` session in user's cargo.toml anymore.

**Comment by jice-nospam** [comment]
There are a few features I need for my current project. I don't want to pollute the uni-xxx crates with stuff that is not needed for a PUBG-like game but in case you want them anyway I can make PR.
Here is what I have so far :

- gamepad support (web : beta, native : not implemented)
- file drag'n drop support - dragging a file from windows explorer to the game window (web: alpha, native: not implemented)
- midi input support (planned)

I intend to build a specific crate for them in my project. Let me know if you rather want some of that inside unrust's uni-app crate.

**Comment by edwin0cheng** [comment]
Gamepad support will be awesome !!

**Comment by edwin0cheng** [comment]
I would think if you could manage to add a new AppEvent for gamepad in current uni-app, it  would be better than adding another uni-xx crate.

**Comment by jice-nospam** [comment]
The problem is that current web api for gamepads is not event based. you're just polling the gamepad's state. The only part that is event based is when you plug or unplug gamepads :
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

You can check the current api here :
https://github.com/jice-nospam/unrust/blob/4a69d73241c628037ace28da4a71418d01689987/uni-app/src/web_app.rs#L279

**Comment by edwin0cheng** [comment]
Um... i see, then i would prefer to add an separate uni_gamepad crate for doing that.

**Comment by jice-nospam** [comment]
ok, I'll make a PR once the sound part is ok

**Comment by edwin0cheng** [comment]
Thanks. 
On the other hand, right now how do you use the shader code? I mean do you share code fragments? Because im going to implement the “#include” features in uni-glsl. Wanna know whether it is useful for you too.

**Comment by jice-nospam** [comment]
Right now I'm using very few shaders but it might still be useful.

**Comment by edwin0cheng** [comment]
Just added #include support in uni_glsl and unrust itself. It is very convenient and allow us to implement a lot of common shader utils and uniforms by it.

Just added `#include "the/path/you/want" in the glsl, that's it. and it handle other #define preprocessor nicely too.

**Comment by edwin0cheng** [comment]
Okay, i think i had tuning the Sponza example enough :)

 So the last thing remain is setup a basic CI which try to build the whole crate and build all examples.

**Comment by edwin0cheng** [comment]
Travis CI is up now. So we finally finish all 0.1.1 features.

**Comment by edwin0cheng** [comment]
Updated Readme to show off some of examples ^^.

And i will close this issue, and open another one for 0.1.2 features

**Comment by jice-nospam** [comment]
awesome! so are we ready to tag?

**Comment by edwin0cheng** [comment]
Yes, will do it tonight, im away from keyboard now.

And i would not publish it in the crate.io now, the api is still very unstable. I prefer to publish it until 0.2.0. Do you think it is okay or want to use it in crate.io now instead?

**Comment by jice-nospam** [comment]
No I think it's fine to wait until things are stabilized

**Comment by edwin0cheng** [comment]
Tagged: 

https://github.com/edwin0cheng/unrust/tree/0.1.1

**Comment by jice-nospam** [comment]
congrats! now to the 0.1.2 !
